const constants = {
	USER_GRADE: {
		SILVER: 'silver',
		GOLD: 'gold',
		PLATINUM: 'platinum',
	},

	MAIL_PROVIDER: {
		EMAIL: 'email',
		GOOGLE: 'google',
	},

	STATUS: {
		CANCELLED: 'cancelled',
		APPROVED: 'approved',
		HOLD: 'hold',
	},

	ADMIN_GRADE: {
		SUPER_ADMIN: 'superadmin',
		ADMIN: 'admin',
	},

	STORE_ADMIN_GRADE: {
		SERVICE: 'service',
		MAINTENANCE: 'maintenance',
		MERCHANDISER: 'merchandiser',
		SUPERVISOR: 'supervisor',
	},

	SOCIAL_PROFILE: {
		NAVER: 'naver',
		KAKAO: 'kakao',
		GOOGLE: 'google',
	},

	JWT_COOKIE: 'x-jwt-cookie',

	REGEX: {
		EMAIL_REGEX: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
		MOBILEPHONE_REGEX: /^(01[016789]{1})[0-9]{3,4}[0-9]{4}$/,
		ENG_NUMBER_REGEX: /^[a-zA-Z0-9]+$/,
		ENG_REGEX: /^[a-zA-Z]*$/,
		KOR_NUMBER_REGEX: /[가-힣0-9]+/,
		KOR_REGEX: /^[가-힣]+$/,
		NUMBER_REGEX: /^[0-9]+$/,
		PASSWORD_REGEX:
			/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?])(?=.{8,}).*$/,
	},

	CATEGORIES_KOR: [
		{
			NAME: '신발',
			ITEMS: [
				'스니커즈',
				'부츠/워커',
				'구두',
				'스포츠화',
				'패딩/퍼 신발',
				'신발 용품',
			],
		},
		{
			NAME: '상의',
			ITEMS: [
				'반소매 티셔츠',
				'셔츠/블라우스',
				'긴소매 티셔츠',
				'니트/스웨터',
				'피케/카라 티셔츠',
				'맨투맨/스웨트',
				'민소매 티셔츠',
				'후드 티셔츠',
				'기타 상의',
			],
		},
		{
			NAME: '아우터',
			ITEMS: [
				'후드 집업',
				'블루종/MA-1',
				'레더/라이더스 재킷',
				'카디건',
				'트러커 재킷',
				'슈트/블레이저',
				'스타디움',
				'나일론/코치',
				'아노락',
				'트레이닝',
				'코트',
				'사파리/헌팅',
				'베스트',
				'숏패딩/헤비아우터',
				'롱패딩/헤비아우터',
				'패딩베스트',
				'무스탕/퍼',
				'플리스',
				'기타 아우터',
			],
		},
		{
			NAME: '바지',
			ITEMS: [
				'데님',
				'트레이닝/조거',
				'코튼',
				'슈트 팬츠/슬랙스',
				'숏 팬츠',
				'레깅스',
				'점프 슈트/오버울',
				'기타 하의',
			],
		},
		{
			NAME: '원피스/스커트',
			ITEMS: [
				'미니원피스',
				'미디원피스',
				'맥시원피스',
				'미니스커트',
				'미디스커트',
				'롱스커트',
			],
		},
		{
			NAME: '가방',
			ITEMS: [
				'메신저/크로스백',
				'숄더백',
				'백팩',
				'토트백',
				'에코백',
				'보스턴/더플백',
				'웨이스트백',
				'파우치백',
				'브리프케이스',
				'캐리어',
				'가방소품',
				'지갑/머니클립',
				'클러치백',
			],
		},
		{
			NAME: '패션소품',
			ITEMS: [
				'모자',
				'머플러',
				'주얼리',
				'양말/레그웨어',
				'선글라스/안경테',
				'액세서리',
				'시계',
				'벨트',
			],
		},
		{
			NAME: '속옷/홈웨어',
			ITEMS: [
				'홈웨어',
				'여성속옷상의',
				'여성속옷하의',
				'여성속옷세트',
				'남성속옷',
			],
		},
		{
			NAME: '스포츠/레저',
			ITEMS: [
				'상의',
				'아우터',
				'상하의세트',
				'하의',
				'스커트',
				'원피스',
				'수영복/비치웨어',
				'신발',
				'기구/용품/장비',
				'가방',
				'잡화',
				'모자',
			],
		},
	],
	CATEGORIES_ENG: [
		{
			NAME: 'SHOES',
			ITEMS: [
				'SNEAKERS',
				'BOOTS / WORKER BOOTS',
				'DRESS SHOES',
				'SPORTS SHOES',
				'PADDED / FUR SHOES',
				'SHOE ACCESSORIES',
			],
		},
		{
			NAME: 'TOPS',
			ITEMS: [
				'SHORT-SLEEVED T-SHIRTS',
				'SHIRTS / BLOUSES',
				'LONG-SLEEVED T-SHIRTS',
				'KNITWEAR / SWEATERS',
				'PIQUE / POLO SHIRTS',
				'SWEATSHIRTS',
				'SLEEVELESS T-SHIRTS',
				'HOODIES',
				'OTHER TOPS',
			],
		},
		{
			NAME: 'OUTERWEAR',
			ITEMS: [
				'HOODED ZIP-UPS',
				'BLOUSON / MA-1 JACKETS',
				'LEATHER / RIDER JACKETS',
				'CARDIGANS',
				'TRUCKER JACKETS',
				'SUITS / BLAZERS',
				'STADIUM JACKETS',
				'NYLON / COACH JACKETS',
				'ANORAKS',
				'TRACKSUITS',
				'COATS',
				'SAFARI / HUNTING JACKETS',
				'VESTS',
				'SHORT PADDING / HEAVY OUTERWEAR',
				'LONG PADDING / HEAVY OUTERWEAR',
				'PADDED VESTS',
				'SHEARLING / FUR',
				'FLEECE',
				'OTHER OUTERWEAR',
			],
		},
		{
			NAME: 'PANTS',
			ITEMS: [
				'DENIM',
				'TRACK PANTS / JOGGERS',
				'COTTON PANTS',
				'SUIT PANTS / SLACKS',
				'SHORTS',
				'LEGGINGS',
				'JUMPSUITS / OVERALLS',
				'OTHER BOTTOMS',
			],
		},
		{
			NAME: 'DRESSES / SKIRTS',
			ITEMS: [
				'MINI DRESSES',
				'MIDI DRESSES',
				'MAXI DRESSES',
				'MINI SKIRTS',
				'MIDI SKIRTS',
				'LONG SKIRTS',
			],
		},
		{
			NAME: 'BAGS',
			ITEMS: [
				'MESSENGER / CROSSBODY BAGS',
				'SHOULDER BAGS',
				'BACKPACKS',
				'TOTE BAGS',
				'ECO BAGS',
				'BOSTON / DUFFEL BAGS',
				'WAIST BAGS',
				'POUCH BAGS',
				'BRIEFCASES',
				'LUGGAGE / CARRIERS',
				'BAG ACCESSORIES',
				'WALLETS / MONEY CLIPS',
				'CLUTCHES',
			],
		},
		{
			NAME: 'FASHION ACCESSORIES',
			ITEMS: [
				'HATS',
				'SCARVES / MUFFLERS',
				'JEWELRY',
				'SOCKS / LEGWEAR',
				'SUNGLASSES / EYEWEAR FRAMES',
				'ACCESSORIES',
				'WATCHES',
				'BELTS',
			],
		},
		{
			NAME: 'UNDERWEAR / LOUNGEWEAR',
			ITEMS: [
				'LOUNGEWEAR',
				"WOMEN'S UNDERWEAR TOPS",
				"WOMEN'S UNDERWEAR BOTTOMS",
				"WOMEN'S UNDERWEAR SETS",
				"MEN'S UNDERWEAR",
			],
		},
		{
			NAME: 'SPORTS / LEISURE',
			ITEMS: [
				'TOPS',
				'OUTERWEAR',
				'TOP AND BOTTOM SETS',
				'BOTTOMS',
				'SKIRTS',
				'DRESSES',
				'SWIMWEAR / BEACHWEAR',
				'SHOES',
				'EQUIPMENT / GEAR',
				'BAGS',
				'MISCELLANEOUS',
				'HATS',
			],
		},
	],
}

export default constants
